# Generated by Django 5.1.4 on 2025-01-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
