# Generated by Django 5.1.4 on 2025-01-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
